/* Generated by autorevision - do not hand-hack! */
#ifndef AUTOREVISION_H
#define AUTOREVISION_H

#define VCS_TYPE		"git"
#define VCS_BASENAME	"ntpsec"
#define VCS_UUID		"5a60ff124237ba5d23101e4ca60016ebeae7cb50"
#define VCS_NUM			14538
#define VCS_DATE		"2018-03-14T14:00:16Z"
#define VCS_BRANCH		"master"
#define VCS_TAG			"NTPsec_1_0_0"
#define VCS_TICK		418
#define VERSION		"1.0.1"

#define VCS_ACTION_STAMP	"2018-03-14T14:00:16Z!derepas@trust-in-soft.com"
#define VCS_FULL_HASH		"1e3fee3026f7e640d7bf81d626588f1d559225a2"
#define VCS_SHORT_HASH		"1e3fee3"

#define VCS_WC_MODIFIED		1

#endif

/* end */
